version: '3.8'

services:
  app:
    image: sukantabala28/node_app:${IMAGE_TAG}
    container_name: node_app
    ports:
      - '5000:5000'
    env_file: .env.prod
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start  
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - '27027:27017'
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
