name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: sukantabala28/node_app
  SSH_HOST: ${{ secrets.VPS_HOST }}
  SSH_USER: ${{ secrets.VPS_USER }}
  SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
  port: ${{ secrets.VPS_PORT }}
  VPS_PROJECT_DIR: /var/www/docker_test/node-express-mongo-app-docarization

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract short SHA
      id: vars
      run: echo "TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      run: |
        docker build -t $DOCKER_IMAGE:${{ steps.vars.outputs.TAG }} .
        docker push $DOCKER_IMAGE:${{ steps.vars.outputs.TAG }}

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ env.SSH_HOST }}
        username: ${{ env.SSH_USER }}
        key: ${{ env.SSH_KEY }}
        port: ${{ env.port }}
        script: |
          cd /var/www/docker_test/node-express-mongo-app-docarization
          git pull origin main
          export IMAGE_TAG=${{ steps.vars.outputs.TAG }}
          echo "IMAGE_TAG=$IMAGE_TAG" > .env
          docker-compose down
          docker-compose -f docker-compose.prod.yml --env-file .env.prod up -d --build
